networks:
  jtools-networking:
    driver: bridge
    external: true

services:
  jtools-db:
    image: postgres:18
    container_name: jtools-db
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - jtools-networking
    environment:
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - jtools_data:/var/lib/postgresql

  jtools-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${JAVA_ENV}
    container_name: jtools-api
    networks:
      - jtools-networking
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - jtools-db
    ports:
      - "${PORT}:${PORT}"
      - "${PORT_DEBUG}:${PORT_DEBUG}"
      - 35729:35729

volumes:
  jtools_data: