spring.application.name=vstream-java

# PORT
server.port=${PORT}

# application.properties
spring.main.web-application-type=servlet
server.error.do.enabled=false
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=11GB

# PostgreSQL Datasource configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
spring.devtools.livereload.enabled=true

